package _Root.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = '4300ba30-27e0-40c8-a606-b6e42fe3846b' (id = 'TestPipeline')
in the project with uuid = '7e725d25-7a02-49e7-83ca-9c6b5b7f0628' and delete the patch script.
*/
create("7e725d25-7a02-49e7-83ca-9c6b5b7f0628", Project({
    uuid = "4300ba30-27e0-40c8-a606-b6e42fe3846b"
    id = "TestPipeline"
    parentId = "_Root"
    name = "Test Pipeline"
}))

