package _Root.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '7e725d25-7a02-49e7-83ca-9c6b5b7f0628' (id = '_Root')
accordingly and delete the patch script.
*/
changeProject("7e725d25-7a02-49e7-83ca-9c6b5b7f0628") {
    params {
        expect {
            password("env.SONAR_LOGIN", "test")
        }
        update {
            password("env.SONAR_LOGIN", "credentialsJSON:0e47334b-423d-47e9-baa8-6ee612ada4d9")
        }
    }

    features {
    }
}
