package _Root.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '8a76bacd-9ae0-48dc-a22f-83d448814b67' (id = '_Root')
accordingly and delete the patch script.
*/
changeProject("8a76bacd-9ae0-48dc-a22f-83d448814b67") {
    params {
        add {
            param("env.sonar_pass", "test")
        }
    }

    features {
        add {
            feature {
                type = "sonar-qube"
                id = "PROJECT_EXT_5"
                param("password", "zxxe142d9c8c80ddf82198a2e44d87fc19c")
                param("name", "Sonar")
                param("id", "8b543757-42d1-4479-9120-a191d80f96ed")
                param("login", "sonar")
                param("url", "https://sonarcloud.io")
            }
        }
    }
}
