package _Root.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with uuid = 'f9e6bc01-f12a-442c-847d-4ccd6f12e3e2' (id = 'TestPipeline_Build')
in the project with uuid = '4300ba30-27e0-40c8-a606-b6e42fe3846b' and delete the patch script.
*/
create("4300ba30-27e0-40c8-a606-b6e42fe3846b", BuildType({
    uuid = "f9e6bc01-f12a-442c-847d-4ccd6f12e3e2"
    id = "TestPipeline_Build"
    name = "Build"

    vcs {
        root("TestPipeline_HttpsGithubComDm0275testPipelineGitRefsHeadsMaster")

    }

    triggers {
        vcs {
        }
    }
}))

