package _Root.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = '31bc7a3f-6ac3-4f09-8190-799a903d7d09' (id = 'TestPipeline_HttpsGithubComDm0275testPipelineGitRefsHeadsMaster')
in the project with uuid = '4300ba30-27e0-40c8-a606-b6e42fe3846b' and delete the patch script.
*/
create("4300ba30-27e0-40c8-a606-b6e42fe3846b", GitVcsRoot({
    uuid = "31bc7a3f-6ac3-4f09-8190-799a903d7d09"
    id = "TestPipeline_HttpsGithubComDm0275testPipelineGitRefsHeadsMaster"
    name = "https://github.com/dm0275/test-pipeline.git#refs/heads/master"
    url = "https://github.com/dm0275/test-pipeline.git"
    authMethod = password {
        userName = "dm0275"
        password = "credentialsJSON:ec3588b9-c678-4667-9dc1-19a3c3ae09f1"
    }
}))

