package _Root.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = 'a88b7f6f-b1be-437c-85ae-433e07623de4' (id = 'testPipeline')
in the project with uuid = '7e725d25-7a02-49e7-83ca-9c6b5b7f0628' and delete the patch script.
*/
create("7e725d25-7a02-49e7-83ca-9c6b5b7f0628", GitVcsRoot({
    uuid = "a88b7f6f-b1be-437c-85ae-433e07623de4"
    id = "testPipeline"
    name = "https://github.com/dm0275/test-pipeline.git"
    url = "https://github.com/dm0275/test-pipeline.git"
    pushUrl = "https://github.com/dm0275/test-pipeline.git"
    authMethod = password {
        userName = "dm0275"
        password = "credentialsJSON:ec3588b9-c678-4667-9dc1-19a3c3ae09f1"
    }
}))

